-- =============================================================================
-- WorkOrderApp — SQLite Schema
-- =============================================================================
-- This file contains the CREATE TABLE statement for the WorkOrders table,
-- which is the single table that powers the Facility Maintenance Work Order
-- Management application.
--
-- The schema is generated by Entity Framework Core (EnsureCreated) from the
-- WorkOrder model class located at: backend/Models/WorkOrder.cs
--
-- To recreate an empty database from this file:
--     sqlite3 workorders.db < schema.sql
-- =============================================================================

CREATE TABLE IF NOT EXISTS "WorkOrders" (
    "Id"              INTEGER NOT NULL CONSTRAINT "PK_WorkOrders" PRIMARY KEY AUTOINCREMENT,
    "WorkOrderNumber" TEXT    NOT NULL,
    "Title"           TEXT    NOT NULL,
    "Description"     TEXT    NULL,
    "Priority"        TEXT    NOT NULL,    -- Allowed values: 'Low', 'Medium', 'High'
    "Status"          TEXT    NOT NULL,    -- Allowed values: 'New', 'Assigned', 'In Progress', 'On Hold', 'Completed', 'Cancelled'
    "CustomerName"    TEXT    NOT NULL,
    "TechnicianName"  TEXT    NULL,
    "EstimatedCost"   TEXT    NULL,        -- Stored as TEXT by EF Core; represents a decimal value
    "CreatedAt"       TEXT    NOT NULL,    -- ISO 8601 UTC timestamp
    "UpdatedAt"       TEXT    NOT NULL     -- ISO 8601 UTC timestamp
);

-- Helpful indexes for the most common filters and lookups used by the API.
CREATE INDEX IF NOT EXISTS "IX_WorkOrders_Status"          ON "WorkOrders" ("Status");
CREATE INDEX IF NOT EXISTS "IX_WorkOrders_Priority"        ON "WorkOrders" ("Priority");
CREATE INDEX IF NOT EXISTS "IX_WorkOrders_WorkOrderNumber" ON "WorkOrders" ("WorkOrderNumber");
CREATE INDEX IF NOT EXISTS "IX_WorkOrders_CreatedAt"       ON "WorkOrders" ("CreatedAt");
